version: '2'

services:
  base:
    image: nexus.company.com/alpine:1
    entrypoint: ["bin/gosu-entrypoint", "bin/configure-app"]
    working_dir: /app
    volumes:
      - .:/app/
      - ./data/var-local:/var/local
      - ./docker/base/apache-vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/base/php.ini:/usr/local/etc/php/conf.d/90-php.ini
      - ~/.ssh/id_rsa:/home/user/.ssh/id_rsa
      - ~/.ssh/known_hosts:/home/user/.ssh/known_hosts
      - ~/.aws:/home/user/.aws
      - ~/.cache/composer:/home/user/composer-cache
      - ~/.config/composer:/home/user/composer
    env_file:
      - .env
    environment:
      REDIS_HOST: "redis:6379"
      REDIS_SESSION_PREFIX: "PHPREDIS_SESSION:"
      REDIS_SESSION_DATABASE: 0
      TZ: "${TIMEZONE}"
      COMPOSER_CACHE_DIR: /home/user/composer-cache

  app:
    extends: base
    entrypoint: ["bin/configure-app"]
    command: ["haproxy-foreground"]
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${LEGACY_API_PORT}:6686"
    links:
      - postgres
      - redis

  dev:
    extends: base
    links:
      - postgres
      - redis
      - app
    environment:
      TEST_BASE_URL: http://app

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgexample
      TZ: "${TIMEZONE}"

  redis:
    image: redis:4.0
    environment:
      TZ: "${TIMEZONE}"
