#!/usr/bin/env bash

# ensures that fox is in path
grep -q "/.fox.bash" "$HOME/.bashrc" && echo "[fox] found bash path. skipping update." || echo "[ -f ~/.fox.bash ] && source ~/.fox.bash" >> $HOME/.bashrc
