#!/usr/bin/env bash

# usage: watch [command] [sleep duration]

if [ -z $1 ]; then 
  echo "usage : watch <interval seconds> <command>";
  echo "        watch 5 echo me";
  exit 0;
fi

ival=${1:-1}
shift
echo "$@"
echo $ival

while :; do 
  clear
  printf "$(date) [ctrl-c to exit] \n\n"
  # bash -c "$@"
  "$@"
  sleep "$ival"
done
